services:
  app:
    build: ./your_quality_programmer
    restart: unless-stopped
    container_name: tutorial
    ports:
      - "8000:8000"
    depends_on:
      - db
#    environment:
#      DEBUG: ${DEBUG}
#      DATABASE_ENGINE: ${DATABASE_ENGINE}
#      DATABASE_NAME: ${DATABASE_NAME}
#      DATABASE_USERNAME: ${DATABASE_USERNAME}
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#      DATABASE_HOST: ${DATABASE_HOST}
#      DATABASE_PORT: ${DATABASE_PORT}
    command: >
      bash -c "
      python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./your_quality_programmer:/code
    develop:
      watch:
        - action: sync
          path: ./your_quality_programmer
          target: /code
          ignore:
            - Dockerfile
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: your-quality-programmer-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: your-quality-programmer-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/ssl/certs/dev:ro

volumes:
  postgres_data:

networks:
  inside-network:
    driver: bridge
